version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '/tinyapp-typescript/src'
      - '/tinyapp-typescript/node_modules'
    ports:
      - 4000:3001
    environment:
      - NODE_ENV=development
